# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# ------------------------------------------------------------------------------

# 1. task for me: create a generator for fib
# 2. create a filter, which just allows even-valued terms
# 3. sum up all those terms until up to 4*10^6
# .. profit!

# ------------------------------------------------------------------------------

def getFibGen():
    pass

# ------------------------------------------------------------------------------

def getNextEvenValue():
    pass

# ------------------------------------------------------------------------------

def problem002():
    print("problem002")
    pass

# ------------------------------------------------------------------------------

problem002()