# Triangular, pentagonal, and hexagonal
#
# Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

# ------------------------------------------------------------------------------
# idea:
# * just borrow from the dove-tailing approach from problem044:
# ** compute first the next hexagonal number, then compute triangle and pentagonal numbers up to this point and
#   put them into respective dicts; then check the given hexagonal number if it is inside the dicts
# * if two hits are found, abort mission .. should be easy as pie; maybe computationally intensive,
#   but should be doable until midnight

# ------------------------------------------------------------------------------

def makeTriangleNumber(n):
    return n * (n + 1) // 2

def makePentagonalNumber(n):
    return n*(3 * n - 1) // 2

def makeHexagonalNumber(n):
    return n*(2 * n - 1)

# ------------------------------------------------------------------------------

triNums = dict()
pentNums = dict()
hexNums = dict()

# init
triNums[1] = 1 # needed for the way how for the maximum key in the dict is searched
pentNums[1] = 1

def findHits(maxAmount):

    n = 1
    while True:
        # compute the current hexagonal number
        if n in hexNums:
            nH = makeHexagonalNumber[n]
        else:
            nH = makeHexagonalNumber(n)
            hexNums[n] = nH

        print("handle now", n, "-->", nH) # todom remove

        # fill the dicts of the tria and pent numbers
        while (currentMax := max(triNums, key=lambda x: triNums[x])) < nH: # assigment in condition is a python 3.8 feature!
            nextKey = currentMax+ + 1
            triNums[nextKey] = makeTriangleNumber(nextKey)
            print("    ", nextKey, triNums[nextKey]) # todom remove

        # todo do the same for pentagonal number dict

        n += 1


findHits(10)
